# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciodiario',
            name='fecha',
            field=models.DateField(),
        ),
    ]
