# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_auto_20161106_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumodiario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preciodiario',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
