# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 23:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0002_auto_20161108_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumodiario',
            name='fecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.PrecioDiario'),
        ),
        migrations.AlterField(
            model_name='preciodiario',
            name='fecha',
            field=models.DateField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='consumodiario',
            unique_together=set([('fecha', 'usuario')]),
        ),
    ]
